kind: Service
apiVersion: v1
metadata:
  name: auth-service
spec:
  type: NodePort
  selector:
    app: auth
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30090

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
      track: stable
  template:
    metadata:
      labels:
        app: auth
        track: stable
    spec:
      containers:
      - name: train-schedule
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        volumeMounts:
        - name: config-data
          mountPath: /usr/local/tomcat/config-app
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m
      volumes:
      - name: config-data
        configMap:
          name: database.prop

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: database.prop
data:
  database.properties: |
    database.driverClassName=com.mysql.jdbc.Driver
    database.url=jdbc\:mysql\://127.0.0.1\:3306/mlpt_vrekon
    database.username=root
    database.password=
